# replace .war with .jar or .ear if needed
name: Whitesource Prioritize Java with Maven

on:
  push:
    branches: [ release* ]
  pull_request:
    branches: [ release* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests=true
      
    - name: appPath Discovery
      run: |
        pwd && echo "pwd"
        ls ./walmartlabs-concord/walmartlabs-concord/runtime/v1/impl/target && echo "ls of walmartlabs-concord/walmartlabs-concord/runtime/v1/impl/target"
        ls ./walmartlabs-concord/walmartlabs-concord/runtime/v2/runner/target && echo "ls of walmartlabs-concord/walmartlabs-concord/runtime/v2/runner/target"
        ls ./walmartlabs-concord/walmartlabs-concord/cli/target && echo "ls of /walmartlabs-concord/walmartlabs-concord/cli/target"
        ls ./walmartlabs-concord/walmartlabs-concord/plugins/tasks/smtp/target && echo "ls of walmartlabs-concord/walmartlabs-concord/plugins/tasks/smtp/target"

        
